import { Inter } from "next/font/google";
import "./globals.css";
import Footer from "./Components/Footer";
import Header from "./Components/Header";
import MyContext  from "./Helper/Context";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body suppressHydrationWarning className={inter.className}>
        <Header/>
        <MyContext>{children}</MyContext>
       <Footer/>
        
        </body>
    </html>
  );
}
